### ISSUE TITLE
Add support for SSH Git URLs

### ISSUE THREAD

**Issue by Octogonapus** [CommonWealthRobotics/bowler-kernel#78]
### Describe the bug

When trying to run a script using an SSH Git URL (e.g. `git@github.com:CommonWealthRobotics/bowler-kernel-test-repo.git`), you are not allowed
```
java.lang.IllegalArgumentException: The supplied Git URL (git@github.com:CommonWealthRobotics/bowler-kernel-test-repo.git) was not a valid repository or Gist URL.
	at com.commonwealthrobotics.bowlerkernel.gitfs.GitHubFS$Companion.gitUrlToDirectory$gitfs(GitHubFS.kt:332)
	at com.commonwealthrobotics.bowlerkernel.gitfs.GitHubFS$cloneRepo$1.invoke(GitHubFS.kt:64)
	at com.commonwealthrobotics.bowlerkernel.gitfs.GitHubFS$cloneRepo$1.invoke(GitHubFS.kt:48)
```

### Expected behavior

We should support SSH URLs.

**Comment by Octogonapus** [comment]
It looks like JGit has trouble with this. Moving to the icebox for now.
